name: Basic Lab CI

# 1. Triggers: When should this run?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 2. Jobs: What tasks should be done?
jobs:
  build-and-test:
    runs-on: ubuntu-latest  # The server OS GitHub will use

    steps:
    # Step A: Download your code to the server
    - uses: actions/checkout@v3

    # Step B: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step C: Run your script to ensure it doesn't crash
    - name: Run the application
      run: python app.py
